var myFavoriteDog = 'Goldendoodle'
var myFavoriteAnimal = 'Tiger'
var myFavoriteHorse = "Blue Roan"
var typesOfDogs = 100
var typesOfTigers = 5
var typesOfHorses = 200
var dogsAreCute = true
var tigersAreScary = true
var horsesAreSmall = false 
